export const PetsActionTypes = {
  PETS_FETCHING: "PETS_FETCHING",
  PETS_FETCHED: "PETS_FETCHED",
  PETS_FETCHING_ERROR: "PETS_FETCHING_ERROR",

  PET_CREATED: "PET_CREATED",
  PET_CREATED_SUCCESS: "PET_CREATED_SUCCESS",
  PET_CREATED_ERROR: "PET_CREATED_ERROR",

  PET_DELETED: "PET_DELETED",
  PET_DELETED_SUCCESS: "PET_DELETED_SUCCESS",
  PET_DELETED_ERROR: "PET_DELETED_ERROR",
};
