export const FormActionTypes = {
  CHANGE_CURRENT_STEP: "CHANGE_CURRENT_STEP",
  CHANGE_CURRENT_FORM_ID: "CHANGE_CURRENT_FORM_ID",
  ADD_USER: "ADD_USER",
  ADD_PET: "ADD_PET",
  RESET_APP: "RESET_APP",
  ADD_FORM_DATA: "ADD_FORM_DATA",
  CHANGE_FORM_DATA: "CHANGE_FORM_DATA",
  CHANGE_CURRENT_FORM_INDEX: "CHANGE_CURRENT_FORM_INDEX",
  CHANGE_PETS: "CHANGE_PETS",
};
