export const FormActionTypes = {
  ADD_USER: "ADD_USER",
  CHANGE_FORM_DATA: "CHANGE_FORM_DATA",
  CHANGE_CURRENT_FORM_INDEX: "CHANGE_CURRENT_FORM_INDEX",
  ADD_PET: "ADD_PET",
  CHANGE_CURRENT_STEP: "CHANGE_CURRENT_STEP",
};
