export const UserActionTypes = {
  USER_FETCHING: "USER_FETCHING",
  USER_FETCHED: "USER_FETCHED",
  USER_FETCHING_ERROR: "USER_FETCHING_ERROR",

  USER_CREATED: "USER_CREATED",
  USER_CREATED_SUCCESS: "USER_CREATED_SUCCESS",
  USER_CREATED_ERROR: "USER_CREATED_ERROR",
};
